### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by vit9696** [TaiPhamD/EFIBootSelector#2]
`VCRUNTIME140D.dll`, `VCRUNTIME140_1D.dll`, and `ucrtbased.dll` are `Debug` versions of MSVC runtime. Please build with `cmake -DCMAKE_BUILD_TYPE=Release` as I am not supposed to install Visual Studio to run a distributed app. I do not see any GCC dependencies in the built apps. What does this refer to?

**Comment by TaiPhamD** [comment]
> `VCRUNTIME140D.dll`, `VCRUNTIME140_1D.dll`, and `ucrtbased.dll` are `Debug` versions of MSVC runtime. Please build with `cmake -DCMAKE_BUILD_TYPE=Release` as I am not supposed to install Visual Studio to run a distributed app. I do not see any GCC dependencies in the built apps. What does this refer to?

Thank you for the feedback. I totally missed the cmake flag to build for release. 

The GCC dependencies are because I am using CGO interop feature to bridge Golang and C++. I have some ideas now to try to use clang-cl to compile CGO so I don't need the extra TDM-GCC dependency. I believe CGO is only compatible with GCC and clang. 

https://devblogs.microsoft.com/cppblog/clang-llvm-support-in-visual-studio/

This document suggests that clang-cl is some kind of clang front end wrapper around msvc compiler so that would be great if it works.

**Comment by TaiPhamD** [comment]
Fixed with [release](https://github.com/TaiPhamD/EFIBootSelector/releases/tag/v0.2.5) build and static link. The dependencies are greatly reduced.
```
Dump of file efidll.dll

File Type: DLL

  Image has the following dependencies:

    ADVAPI32.dll
    KERNEL32.dll
    msvcrt.dll

Dump of file efiserver.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    msvcrt.dll

Dump of file eficlient.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    kernel32.dll

```
